apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-openshift
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-openshift
  template:
    metadata:
      labels:
        app: demo-openshift
    spec:
      containers:
        - name: demo-openshift
          image: image-registry.openshift-image-registry.svc:5000/dmp/demo-openshift:latest
          ports:
            - containerPort: 8085
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
  triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - demo-openshift
        from:
          kind: ImageStreamTag
          name: demo-openshift:latest
          namespace: dmp
    - type: ConfigChange
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/generated-by: demo-openshift
  labels:
    app: demo-openshift
    template: demo-openshift
  name: demo-openshift
  namespace: dmp
spec: {}
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: demo-openshift
spec:
  source:
    type: Git
    git:
      uri: https://github.com/lewisyingliu/demo-openshift.git
      ref: main
    contextDir: ""
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: demo-openshift:latest